### ISSUE TITLE
a broken demo example after jumping

### ISSUE THREAD

**Issue by ondrek** [igorski/zCanvas#3]
Hello, dear developer Igor.

In the provided demo (https://rawgit.com/igorski/zCanvas/master/examples/demo1.html) there is a weird behaviour after I try run into a wall. I think the coordinates are somehow moved, so I'm not able to jump again. 

Problem:
I'm not able to jump again on the stair. 

Browser and OS:
The latest OsX and Chrome, but pretty sure it's the same everywhere.

I'm providing a video that is self-explanatory.
https://youtu.be/amhBvwxIe5g?t=21s

**Comment by ondrek** [comment]
:snail:

Hello — I'm not very satisfied with progress of this task. 
Does the issue has any progress so far?

**Comment by igorski** [comment]
Hi ondrek, excuse the zCanvas team. We were under the assumption that this ticket was an announcement of a contribution on the collision detection algorithm. Guess we were mistaken!

**Comment by igorski** [comment]
Hi @ondrek the collision detection routine has been optimized in the latest release (3.0) of zCanvas. This should resolve the issues on display in your video.
